build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}


    steps:


    - name: Sparse checkout
      shell: bash
      run: |
        REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        BRANCH="${GITHUB_REF/#refs\/heads\//}"
        echo "Syncing repository: $GITHUB_REPOSITORY"
        echo "Working directory is '$(pwd)' GITHUB_WORKSPACE=$GITHUB_WORKSPACE BRANCH=$BRANCH"
        git version
        git init $GITHUB_WORKSPACE
        git remote add origin https://github.com/$GITHUB_REPOSITORY
        git config --local gc.auto 0
        git config core.protectNTFS false
        git -c protocol.version=2 fetch --no-tags --prune --progress --depth=10 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
        git sparse-checkout set --no-cone '/*' '!examples' '!docs'
        git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH


    - name: Install Prerequisites
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-qt6-base
          mingw-w64-x86_64-qt6-tools
          mingw-w64-x86_64-qt6-translations
          mingw-w64-x86_64-readline
          mingw-w64-x86_64-zlib


    - name: Build SWORD
      run: |
        wget https://www.crosswire.org/ftpmirror/pub/sword/source/v1.9/sword-1.9.0.tar.gz
        mkdir orig
        cd orig
        tar xzf ../sword-1.9.0.tar.gz || true
        patch -i ../sword-patch-mingw64.diff -p1
        cd sword-1.9.0
        mkdir build
        cd build
        # Install SWORD in /mingw64 (which is usually C:/msys64/mingw64 on normal installations):
        CC=clang CXX=clang++ cmake -DCMAKE_INSTALL_PREFIX=/mingw64 -G "MinGW Makefiles" ..
        mingw32-make install


    - name: Build bibref-qt
      run: |
        cd qt
        mkdir build
        cd build
        CC=clang CXX=clang++ cmake -G "MinGW Makefiles" ..
        mingw32-make
